@host=http://localhost:9090

### create user
POST {{host}}/users
Content-Type: application/json

{
  "username": "jane_doe",
  "email": "jane.doe@example.com",
  "password": "securepassword123",
  "bio": "Fitness enthusiast"
}

### authenticate
POST {{host}}/tokens/auth
Content-Type: application/json

{
  "username": "jane_doe2",
  "password": "securepassword123"
}

### create workout
POST {{host}}/workouts
Content-Type: application/json
Authorization: Bearer GZPLMKKVOXLXIO6M5SKTXNHHQFIMJRXGZQAMJFWZGLYXPFEF4E4Q

{
  "title": "Morning Strength Training",
  "description": "Full body strength training session",
  "duration_minutes": 60,
  "calories_burned": 500,
  "entries": [
    {
      "exercise_name": "Squats",
      "sets": 3,
      "reps": 12,
      "weight": 100.5,
      "notes": "Felt strong today",
      "order_index": 1
    },
    {
      "exercise_name": "Bench Press",
      "sets": 4,
      "reps": 10,
      "weight": 80.0,
      "notes": "Increase weight next session",
      "order_index": 2
    }
  ]
}

### Update Workout
PUT {{host}}/workouts/3
Content-Type: application/json
Authorization: Bearer GZPLMKKVOXLXIO6M5SKTXNHHQFIMJRXGZQAMJFWZGLYXPFEF4E4Q

{
  "title": "Updated Full Body Strength Training",
  "description": "A more intense strength training session",
  "duration_minutes": 75,
  "calories_burned": 600,
  "entries": [
    {
      "exercise_name": "Deadlifts",
      "sets": 4,
      "reps": 8,
      "weight": 125.0,
      "notes": "Increase weight gradually",
      "order_index": 1
    },
    {
      "exercise_name": "Pull-Ups",
      "sets": 3,
      "reps": 10,
      "notes": "Focus on form",
      "order_index": 2
    },
    {
      "exercise_name": "Plank",
      "sets": 3,
      "duration_seconds": 90,
      "notes": "Increase duration",
      "order_index": 3
    }
  ]
}


### get workout
GET {{host}}/workouts/3

### delete workout
DELETE {{host}}/workouts/3
Authorization: Bearer GZPLMKKVOXLXIO6M5SKTXNHHQFIMJRXGZQAMJFWZGLYXPFEF4E4Q
